openspace/apps/profiles/urls.py
from django.conf.urls import patterns, url
from apps.profiles import views

urlpatterns = patterns('',
    #/profiles/
    url(r'^$', views.index, name='index'),
    #/profiles/5/
    url(r'^(?P<profile_id>\d+)/$',
        views.single, name='single'),
    #/profiles/5/friends/
    url(r'^(?P<profile_id>\d+)/friends/$',
        views.friends, name='friends'),
    #/profiles/5/tags/
    url(r'^(?P<profile_id>\d+)/tags/$',
        views.profileTags, name='profileTags'),
    #/profiles/5/death/
    url(r'^(?P<profile_id>\d+)/death/$',
        views.profileDeath, name='profileDeath'),
    #/profiles/5/addtags/
    url(r'^(?P<profile_id>\d+)/addtags/$',
        views.addProfileTags, name='addProfileTags'),
    #/profiles/5/profileinterest/
    url(r'^(?P<profile_id>\d+)/profileinterest/$',
        views.profileInterest, name='profileInterest'),
    #/profiles/5/makefriend/
    url(r'^(?P<profile_id>\d+)/makefriend/$',
        views.makeFriend, name='makeFriend'),
    #/profiles/5/post/5/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/$',
        views.singlePost, name='singlePost'),
    #/profiles/5/post/5/addtags/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/addtags/$',
        views.addPostTags, name='addPostTags'),
    #/profiles/post/5/postinterest/
    url(r'^post/(?P<post_id>\d+)/postinterest/$',
        views.postInterest, name='postInterest'),
    #/profiles/5/post/5/addcomment/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/addcomment/$',
        views.addComment, name='addComment'),
    #/profiles/5/eatprofile/
    url(r'^(?P<profile_id>\d+)/eatprofile/$',
        views.eatProfile, name='eatProfile'),
    #/profiles/5/graze/
    url(r'^(?P<profile_id>\d+)/graze/$',
        views.grazeProfile, name='grazeProfile'),
    #/profiles/5/post/5/graze/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/graze/$',
        views.grazePost, name='grazePost'),
    #/profiles/createprofile/2/
    url(r'^createprofile/(?P<species_id>\d+)/$',
        views.createProfile, name='createProfile'),
)

openspace/apps/tags/urls.py
from django.conf.urls import patterns, url
from apps.tags import views

urlpatterns = patterns('',
    #/tags/
    url(r'^$', views.tags, name='tags'),
    #/tags/2/
    url(r'^(?P<tag_id>\d+)/$',
        views.tag, name='tag'),
    #/tags/2/selecttrail
    url(r'^(?P<tag_id>\d+)/selecttrail/$',
        views.selectTrail, name='selectTrail'),
)

openspace/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.cache import cache_page
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from django.contrib import admin
from apps.profiles.models import Profile
from openspace import views
from sitemap import *

admin.autodiscover()

handler404 = 'views.openspace404'
handler500 = 'views.openspace500'

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^data/$', views.dataPage, name='dataPage'),
    url(r'^help/$', views.helpPage, name='helpPage'),
    url(r'^credits/$', views.creditsPage, name='creditsPage'),
    url(r'^profiles/', include('apps.profiles.urls', namespace='profiles')),
    url(r'^tags/', include('apps.tags.urls', namespace='tags')),
    url(r'^search/$', views.parkSearch, name='parkSearch'),
    url(r'^topprofiles/$', views.topProfiles, name='topProfiles'),
    url(r'^topposts/$', views.topPosts, name='topPosts'),
    url(r'^changebg/$', views.changeBg, name='changeBg'),
    url(r'^humanentry/(?P<human_key>\d+)$', views.humanEntry, name='humanEntry'),
    url(r'^resetsession/$', views.resetSession, name='resetSession'),
    url(r'^nonewsession/', views.noNewSession, name='noNewSession')
)


# here be monsters ... and sitemap garbage
info_dict = {
    'queryset': Profile.objects.all(),
    'date_field': 'date_published'
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'profiles': GenericSitemap(info_dict, priority=0.6),
}

urlpatterns += patterns('',
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

openspace/apps/tags/models.py
from django.db import models

# TAG MODEL
class Tag(models.Model):
    """Tag model can be applied to Profiles and Posts.
    
    Tags consist of a Tag name and an interest value based on how many times a Tag
    had been applied. 
    Trails of similarly tagged Profiles are automatically created for navigation
    """
    
    name = models.CharField(max_length=15)
    interest = models.PositiveIntegerField(max_length=6, default=0)
    
    @property
    def interestString(self):
        return str(self.interest)
    
    def __unicode__(self):
        return self.name

openspace/apps/profiles/forms.py
from django import forms
from apps.profiles.models import Comment
from apps.tags.models import Tag

class CommentForm(forms.ModelForm):
    
    class Meta:
        auto_id = False
        model = Comment
        fields = ('comment_content',)
        widgets = {
            'comment_content': forms.Textarea(
                attrs = {'cols': 68, 'rows': 7, 'class': 'allRound'}),
        }
        
class PostTagForm(forms.Form):
    post_new_tags = forms.CharField(label='',
        widget = forms.TextInput(attrs={'size':'93', 'class': 'formP'}))

class ProfileTagForm(forms.Form):
    pro_new_tags = forms.CharField(label='', widget = forms.TextInput(attrs={'size': '54'}))

openspace/apps/profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from apps.profiles.models import Profile, Post, Comment
from apps.tags.models import Tag
from apps.profiles.forms import CommentForm, ProfileTagForm, PostTagForm
from libs.siteEnums import System, Tags
from libs import siteHelpers, profileHelpers
import re

#/profiles/
def index(request):
    return redirect('index')

#/profiles/<profile_id>/    
def single(request, profile_id):
    """Displays a single Profile and show paginated Posts"""
    profile = get_object_or_404(Profile.objects.prefetch_related('post_set', 'tags'),
        pk=profile_id)
    request.session['nav_position'] = profile.position
    request.session['nav_id'] = profile_id
    allPosts = profile.post_set.all().prefetch_related('comment_set', 'tags')
    posts = Paginator(allPosts, System.postsPage)
    page = request.GET.get('page')
    try:
        pagedPosts = posts.page(page)
    except PageNotAnInteger:
        pagedPosts = posts.page(1)
    except EmptyPage:
        pagedPosts = posts.page(posts.num_pages)
    context = {
        'profile': profile,
        'posts': pagedPosts,
        'comment_form': CommentForm(auto_id=False),
        'profile_tag_form': ProfileTagForm(auto_id=False),
        'post_tag_form': PostTagForm(auto_id=False),
        'auto_tags': Tag.objects.filter(id__gt=System.reservedTags).order_by('-interest','name')[:30],
        'grazable': True
    }
    return render(request, 'profiles/single-profile.html', context)

#/profiles/<profile_id>/friends/
def friends(request, profile_id):
    """Displays all friends of a Profile."""
    profile = get_object_or_404(Profile.objects.select_related('friends'), pk=profile_id)
    context = {
        'profile': profile,
        'profile_tag_form': ProfileTagForm(auto_id=False),
        'auto_tags': Tag.objects.filter(id__gt=System.reservedTags).order_by('-interest','name')[:30]
    }
    return render(request, 'profiles/friends.html', context)

#/profiles/<profile_id>/makefriend/
def makeFriend(request, profile_id):
    """Adds current profile to user's friends set and returns to referrer. Makes a user post."""
    friend = get_object_or_404(Profile, pk=profile_id)
    user = Profile.objects.get(id=request.session['session_id'])
    if friend not in user.friends.all():
        request.session['notification'] = 'friends'
        user.friends.add(friend)
        user.save()
        friend.friends.add(user)
        friend.save()
        postOut = 'made friends with ' + friend.fullName
        profileHelpers.makeUserPost(request, postOut, 'friends')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

#/profiles/<profile_id>/tags/
def profileTags(request, profile_id):
    """Displays all Tags attached to a Profile."""
    profile = get_object_or_404(Profile.objects.prefetch_related('tags'), pk=profile_id)
    context = {
        'profile': profile,
        'profile_tag_form': ProfileTagForm(auto_id=False),
        'auto_tags': Tag.objects.filter(id__gt=System.reservedTags).order_by('name')[:30]
    }
    return render(request, 'profiles/tags.html', context)

#/profiles/<profile_id>/death/
def profileDeath(request, profile_id):
    """Takes a profile id makes a death post and delivers you to profile page.
    NOTE: Profile should already be dead by the time it gets here."""
    profile = get_object_or_404(Profile, pk=profile_id)
    if profile.isDead:
        profileHelpers.makeDeathPost(profile)
        request.session['notification'] = 'starvation'
        request.session['nav_position'] = profile.position
    return redirect('profiles:single', profile.id)
    
#/profiles/<profile_id>/post/<post_id>/
def singlePost(request, profile_id, post_id):
    """Displays a single Post from a Profile."""
    profile = get_object_or_404(Profile.objects.prefetch_related('post_set'), pk=profile_id)
    post = get_object_or_404(Post.objects.prefetch_related('comment_set', 'tags'), pk=post_id)
    request.session['nav_position'] = profile.position
    request.session['nav_id'] = profile_id
    request.session['is_human'] = True
    context = {
        'profile': profile,
        'post': post,
        'comment_form': CommentForm(auto_id=False),
        'profile_tag_form': ProfileTagForm(auto_id=False),
        'post_tag_form': PostTagForm(auto_id=False),
        'auto_tags': Tag.objects.filter(id__gt=System.reservedTags).order_by('name')[:30],
        'grazable': True
        }
    return render(request, 'profiles/single-post.html', context)

#/profiles/<profile_id>/post/<post_id>/addcomment/
def addComment(request, profile_id, post_id):
    """Adds a comment a Post and returns to referrer. Makes a user post."""
    profile = get_object_or_404(Profile, pk=profile_id)
    post = get_object_or_404(Post, pk=post_id)
    context = {'profile': profile, 'post': post}
    if request.POST:
        form = CommentForm(request.POST)
        if form.data['comment_content'] and form.is_valid:
            new_comment = form.save(commit=False)
            new_comment.comment_content = re.sub('<[^<]+?>', '', form.data['comment_content'])
            new_comment.comment_profile = Profile.objects.get(id=request.session['session_id'])
            new_comment.comment_post = post
            new_comment.date_published = timezone.now()
            new_comment.save()
            postOut = 'left comment: ' + new_comment.comment_content
            profileHelpers.makeUserPost(request, postOut, 'comment')
            request.session['notification'] = 'comment'
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return redirect('profiles:singlePost', profile_id, post_id)

#/profiles/5/profileinterest/
def profileInterest(request, profile_id):
    """Adds interest to a Profile. Makes a user post."""
    profile = get_object_or_404(Profile, pk=profile_id)
    interestSet = request.session['profile_interest_collection'].split(',')
    if profile_id not in interestSet and profile_id != request.session['session_id']:
        siteHelpers.upInterest(profile)
        request.session['profile_interest_collection'] += ',' + profile_id
        postOut = 'likes ' + profile.fullName
        profileHelpers.makeUserPost(request, postOut, 'interest')
        request.session['notification'] = 'likeprofile'
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

#/profiles/post/5/postinterest/
def postInterest(request, post_id):
    """Adds interest to a Post. Makes a user post."""
    post = get_object_or_404(Post, pk=post_id)
    interestSet = request.session['post_interest_collection'].split(',')
    if post_id not in interestSet:
        siteHelpers.upInterest(post)
        request.session['post_interest_collection'] += ',' + post_id
        postOut = 'likes ' + post.postProfileName + '\'s post'
        profileHelpers.makeUserPost(request, postOut, 'interest')
        request.session['notification'] = 'likepost'
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    
#/profiles/5/addtags
def addProfileTags(request, profile_id):
    """Adds Tags to a Profile. Makes a user post."""
    profile = get_object_or_404(Profile, pk=profile_id)
    context = {'profile': profile}
    if request.POST:
        form = ProfileTagForm(request.POST)
        if form.is_valid:
            new_tags = form.data['pro_new_tags']
            addedTags =  siteHelpers.addTags(profile, new_tags.split(','))
            if addedTags:
                postOut = 'added tags: ' + addedTags
                profileHelpers.makeUserPost(request, postOut, 'tag')
                request.session['notification'] = 'tagprofile'
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return redirect('profiles:single', profile_id)

#/profiles/5/post/5/addtags
def addPostTags(request, profile_id, post_id):
    """Adds Tags to a Post. Makes a user post."""
    profile = get_object_or_404(Profile, pk=profile_id)
    post = get_object_or_404(Post, pk=post_id)
    context = {'profile': profile, 'post': post}
    if request.POST:
        form = PostTagForm(request.POST)
        if form.is_valid:
            new_tags = form.data['post_new_tags']
            addedTags = siteHelpers.addTags(post, new_tags.split(', '))
            if addedTags:
                postOut = 'added tags: ' + addedTags
                profileHelpers.makeUserPost(request, postOut, 'tag')
                request.session['notification'] = 'tagpost'
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    #TODO error massage
    return redirect('profiles:post', profile_id, post_id)

#/profiles/createprofile/2
def createProfile(request, species_id):
    """Creates a new Profile of species type species_id."""
    if not siteHelpers.isPredatorPrey(species_id):
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    if not request.session['session_lock']:
        newP = profileHelpers.makeProfile(int(species_id))
        request.session['session_id'] = newP.id
        request.session['session_species'] = newP.species
        request.session['session_lock'] = True
        request.session['notification'] = 'birth'
    return redirect('profiles:single', newP.id)
    
#/profiles/5/eatprofile
def eatProfile(request, profile_id):
    """Makes a selected Profile die and sends notice."""
    prey = get_object_or_404(Profile, pk=profile_id)
    predator = Profile.objects.get(id=request.session['session_id'])
    if profileHelpers.eatPrey(predator, prey):
        request.session['notification'] = 'predation'
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    
#/profiles/5/graze
def grazeProfile(request, profile_id):
    """Consumes text from content of a randomly selected Post of current Profile."""

openspace/apps/tags/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from apps.profiles.models import Profile
from apps.tags.models import Tag
from libs import profileHelpers, siteHelpers
from libs.siteEnums import Tags

#/tags/
def tags(request):
    context = {'tags': Tag.objects.exclude(interest=0).filter(id__gt=7).order_by('name')}
    return render(request, 'tags/trails.html', context)

#/tags/<tag_id>/
def tag(request, tag_id):
    """Display paginate Profiles assigned to current Tag."""
    tag = get_object_or_404(Tag.objects.prefetch_related('profile_set'), pk=tag_id)
    unpagedProfiles = Profile.objects.filter(tags=tag).order_by('-interest')
    pagedResults = siteHelpers.paginatorMaker(unpagedProfiles, request.GET.get('page'), 25)
    context = {
        'special': True,
        'tag': tag,
        'count': unpagedProfiles.count(),
        'paged_results': pagedResults
    }
    return render(request, 'profile-results.html', context)
    
#/tags/<tag_id>/selecttrail/
def selectTrail(request, tag_id):
    """Assigns a Tag to user's session navigation."""
    tag = get_object_or_404(Tag, pk=tag_id)
    if tag.interest > 0:
        if request.session['selected_trail'] == tag.name:
            request.session['selected_trail'] = 'no'
            request.session['notification'] = 'trail'
        else:
            request.session['selected_trail'] = tag.name
            request.session['notification'] = 'trail'
    else:
        request.session['notification'] = 'nope'
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

openspace/templates/background-style.html
<style type="text/css">html { 
background: url({{ STATIC_URL }}{{ background }}) no-repeat center center fixed #141414;
-webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;
}</style>

openspace/templates/index.html
{% extends 'sub-base.html' %}
{% block pagetitle %}wilderness{% endblock %}
{% block body %}
<div id="help" class="box emblem head">
    <div class="content">
        <div class="contentBlock bigBlock justify">
            <h3>[ openspace ] primer</h3>
            <div><p><strong>Hello visitor</strong>, and welcome to the <strong>[openspace] wilderness</strong> - a preserve of virtual space encompassing <strong>[{{ mb_size }} square MB]</strong> of {{ abandoned_count }} abandoned social-network profiles as well a dynamic population of wildlife and visitors. The concrete collapse of Detroit left an empty shell to be picked over, explored, and reinhabited. What is left in the virtual ruins of MySpace or similarly vacated digital social spaces? The abandoned profiles which account for the bulk of the park's area have been created by gathering the posts of long-neglected blogs. The names have been changed to protect the innocent, however the content of the abandoned profiles in the park is directly pulled from the posts of the recovered blogs. Visitors to the park are welcome to view, <strong>[tag]</strong>, like - <strong>[+]</strong>, and <strong>[comment]</strong> the forgotten posts and profiles they encounter while exploring the site on - <strong>[@]</strong> or off - <strong>[&ndash;]</strong> <strong>[trails]</strong>.</p>
            <p>Additionally, Visitors may opt to experience the park as either a <strong>[predator]</strong> or a <strong>[forager]</strong> which entreats them to certain abilities and actions - <strong>[predators]</strong> may <strong>[eat]</strong> prey they encounter, whereas <strong>[foragers]</strong> may <strong>[graze]</strong> post content. As one of these active profiles, your <strong>[energy]</strong> will be depleted and you may eventually die of starvation if you don't consume a foodsource while you explore the park. As profiles die, the site will become littered with the virtual bodies of the dead explorers, opportunists, and colonizers that have wandered into its bounds.</p>
            <p>The wilderness is a finite and consumable resource. You are among the first human eyes to gaze upon much of this content in many years. Your actions effect the whole of the park and it may be preserved and mapped or overrun and overgrazed based on the behavior of those who choose to visit.</p>
            <p>for detailed instructions, visit the <a class="mono" href="{% url 'helpPage' %}">[help page]</a></p>
            </div>
        </div>
        
        <div class="contentBlock smallBlock"><h3>[ key ]</h3>
        <p><span class="mono dark">[@]</span> - select trail<br/>
        <span class="mono dark">[-]</span> - deselect trail<br/>
        <span class="mono dark">[f]</span> - add profile as friend<br/>
        <span class="mono dark">[+]</span> - add interest<br/>
        <span class="mono dark">[tag]</span> - add tag(s)<br/>
        <span class="mono dark">[comment]</span> - add comment</p>
        
        <h3>[ definitions ]</h3>
        <p><span class="mono dark">[trail]</span> - an explorable area of the park linked by a <span class="mono dark">[tag]</span><br/>
        <span class="mono dark">[predator]</span> - consumes active profiles for energy<br/>
        <span class="mono dark">[forager]</span> - grazes the content of posts for energy<br/>
        <span class="mono dark">[energy]</span> - the consumable resource of active profiles</p>
        
        <p class="small justify"><em>The <strong>[openspace] wilderness</strong> is a 2013 commission of New Radio and Performing Arts, Inc., for its <a href="http://www.turbulence.org" target="_blank">Turbulence.org</a> website. It was made possible with funding from the National Endowment for the Arts. <strong><a href="http://www.turbulence.org">[back to Turbulence]</a></strong></em></p>
        </div>
        
        <div class="contentBlock smallBlock lastR"><h3>[ wilderness data ]</h3>
        <p><span class="mono dark">[{{ abandoned_pop }}]</span> abandoned profiles<br/>
        <span class="mono dark">[{{ post_pop }}]</span> abandoned posts<br/>
        <span class="mono dark">[{{ predator_pop }}]</span> living predator{% if predator_pop != 1 %}s{% endif %}<br/>
        <span class="mono dark">[{{ forager_pop }}]</span> living forager{% if forager_pop != 1 %}s{% endif %}<br/>
        <span class="mono dark">[{{ dead_pop }}]</span> dead thing{% if dead_pop != 1 %}s{% endif %}<br/>
        <span class="mono dark">[{{ visitor_pop }}]</span> visitors to date</p>
        
        <p><span class="mono dark">[{{ percent_tagged }}%]</span> park tagged<br/>
        <!-- <span class="mono dark">[{{ percent_dead }}%]</span> park profiles dead<br/> -->
        <span class="mono dark">[{{ percent_grazed }}%]</span> park content grazed</p>
    
        <p><span class="mono dark">[{{ protected_posts }}]</span> posts protected<br/>
        <span class="mono dark">[{{ percent_protected }}%]</span> percent protected</p>
        </div>
        <div class="clear"></div>
    </div>
</div>

<div class="box">
    <div class="heading">
        <h3>interesting <a href="{% url 'topProfiles' %}">[ profiles ]</a></h3>
        <div class="auxAct small mono"><a href="{% url 'topProfiles' %}">[more]</a></div>
    </div>
    <div class="content">
        {% include 'profiles-display.html' %}
    </div>
</div>

{% if posts %}
<div class="box">
    <div class="heading">
        <h3>interesting <a href="{% url 'topPosts' %}">[ posts ]</a></h3>
        <div class="auxAct small mono"><a href="{% url 'topPosts' %}">[more]</a></div>
    </div>
    <div class="content">
        {% for post in posts %}
        <a href="{% url 'profiles:singlePost' post.post_profile.id post.id %}"><div class="wideListing textBlock">
            <p>{{ post.fitContent }}. . .</p>
        </div></a> 
        {% endfor %}
        {% else %}
            <p class="vCenter">nothing here, move along please</p>
        {% endif %}
        <div class="clear"></div>
    </div>
</div>

<div class="box">
    <div class="heading">
        <h3>interesting <a href="{% url 'tags:tags' %}">[ trails ]</a></h3>
    </div>
    <div class="content">
        {% for tag in tags %}
            <div class="wideListing">
            <a href="{% url 'tags:selectTrail' tag.id %}">[ {% if selected_trail == tag.name %}&ndash;{% else %}@{% endif %} ]</a> <a href="{% url 'tags:tag' tag.id %}">{{ tag.name }}</a> [ {{ tag.interest }} ]
            </div>
        {% endfor %}
        <div class="clear butt"></div>
    </div>
</div>

<div class="box">
    <div class="heading">
        <h3>latest [ comments ]</h3>
    </div>
    <div class="content">
        {% for comment in recent_comments %}
            <a href="{% url 'profiles:singlePost' comment.commentPostProfileId comment.commentPostId %}"><div class="wideListing tight">
                <h5>{{ comment.comment_profile }}</h5>
                <h5>{{ comment.date_published }}</h5>
                <p>{{ comment.comment_content }}</p>
            </div></a>
        {% endfor %}
        <div class="clear"></div>
    </div>
</div>
{% endblock %}

openspace/templates/results.html
{% extends 'sub-base.html' %}
{% block pagetitle %} wilderness{% endblock %}
{% block body %}
<div class="box">
    <div class="heading">
        {% if special %}<h3><a href="{% url 'tags:selectTrail' tag.id %}">[ {% if selected_trail == tag.name %}&ndash;{% else %}@{% endif %} ]</a> {{ tag.name }} [ {{ count }}  ]</h3>
        {% else %}<h3>{{ heading }}</h3>{% endif %}
        <div id="pagination" class="auxAct mono small">
            {% if paged_results.has_previous %}
            <a href="?{{ query }}page={{ paged_results.previous_page_number }}"><<</a>
            {% endif %}
            {{ paged_results.number }} of {{ paged_results.paginator.num_pages }}
            {% if paged_results.has_next %}
            <a href="?{{ query }}page={{ paged_results.next_page_number }}">>></a>
            {% endif %}
        </div>
    </div>
    <div class="content">
        {% block results %}{% endblock %}
    </div>
</div>
{% endblock %}

openspace/templates/session-hud.html
<div id="hud" class="flat roundBottom">
    <div class="sessionBlock fright top">
        <div id="sessionInfo" class="fleft"><h4><a href="{% url 'profiles:single' session_id %}">{{ session_name }}</a></h4>
            {% if session_species == predator %}<h4><em>predator</em><br/>kills [ {{ species_meals }} ]</h4>
            {% elif session_species == forager %}<h4><em>forager</em><br/>grazed [ {{ species_meals }} ]</h4>
            {% else %}<h4><em>park visitor</em></h4>{% endif %}
        </div>
        <div id="sessionIcon">
            <a href="{% url 'profiles:single' session_id %}"><img class="round" src="{{ STATIC_URL }}{{ session_icon }}" alt="session profile icon" /></a>
        </div>
    </div>
    <div class="clear"></div>
    <div id="sessionAction" class="sessionBlock topLine">
        <h4>{% if selected_trail != 'no' %}<a href="{% url 'tags:selectTrail' selected_trail_id %}">[ &ndash; ]</a> <a href="{% url 'tags:tag' selected_trail_id %}">[ {{ selected_trail }} ]</a>{% else %}no{% endif %} trail selected</h4>
        {% if not session_lock %}<div id="sessionBlock">
            <h4><a data-mark="speciesSelect" class="toggle">[ select species ]</a></h4>
            <div id="speciesSelect" class="hiddenToggle"><br/><h4>eat active profiles - <a href="{% url 'profiles:createProfile' 3 %}">[ predator ]</a><br/>
            graze post content - <a href="{% url 'profiles:createProfile' 4 %}">[ forager ]</a></h4></div>
        </div>{% endif %}
        {% if is_pred_prey %}
        <p><span class="large{% if session_energy <= 10 %} warning{% endif %}">[ {{ session_energy }} ]</span><br/><em>energy</em></p>
        {% if kosher %}{% if is_post %}<a href="{% url 'profiles:grazePost' profile.id post.id %}">{% else %}<a href="{% url 'profiles:grazeProfile' profile.id %}">{% endif %}<div class="button graze">graze</div></a>
        {% elif prey %}<a href="{% url 'profiles:eatProfile' profile.id %}"><div class="button eat">eat</div></a>{% endif %}
        {% endif %}
    </div>
</div>

{% if session_activity %}<div id="activityBox">
    {% for post in session_activity %}
    <div class="box small miniPost {% if forloop.first and post.justPosted %}latestAction{% endif %}">
        <a href="{% url 'profiles:singlePost' session_id post.id %}"><div class="content">
            <h5 class="strong">{{ post.date_published|date:"F j, Y - fA" }}</h5>
            <p>{{ post.post_content }}</p>
            </div></a>
        </div>{% endfor %}
</div>{% endif %}

openspace/templates/sub-base.html
{% extends 'base.html' %}
{% block bruce_banner %}<div id="banner">
    <img {% if is_human %}class="jsSteadyFade"{% endif %} src="{{ STATIC_URL }}{{ banner }}" alt="page banner" />
</div>{% endblock %}
{% block body %}{% endblock %}