openspace/apps/profiles/urls.py
from django.conf.urls import patterns, url
from apps.profiles import views

urlpatterns = patterns('',
    #/profiles/
    url(r'^$', views.index, name='index'),
    #/profiles/5/
    url(r'^(?P<profile_id>\d+)/$',
        views.single, name='single'),
    #/profiles/5/friends/
    url(r'^(?P<profile_id>\d+)/friends/$',
        views.friends, name='friends'),
    #/profiles/5/tags/
    url(r'^(?P<profile_id>\d+)/tags/$',
        views.profileTags, name='profileTags'),
    #/profiles/5/death/
    url(r'^(?P<profile_id>\d+)/death/$',
        views.profileDeath, name='profileDeath'),
    #/profiles/5/addtags/
    url(r'^(?P<profile_id>\d+)/addtags/$',
        views.addProfileTags, name='addProfileTags'),
    #/profiles/5/profileinterest/
    url(r'^(?P<profile_id>\d+)/profileinterest/$',
        views.profileInterest, name='profileInterest'),
    #/profiles/5/makefriend/
    url(r'^(?P<profile_id>\d+)/makefriend/$',
        views.makeFriend, name='makeFriend'),
    #/profiles/5/post/5/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/$',
        views.singlePost, name='singlePost'),
    #/profiles/5/post/5/addtags/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/addtags/$',
        views.addPostTags, name='addPostTags'),
    #/profiles/post/5/postinterest/
    url(r'^post/(?P<post_id>\d+)/postinterest/$',
        views.postInterest, name='postInterest'),
    #/profiles/5/post/5/addcomment/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/addcomment/$',
        views.addComment, name='addComment'),
    #/profiles/5/eatprofile/
    url(r'^(?P<profile_id>\d+)/eatprofile/$',
        views.eatProfile, name='eatProfile'),
    #/profiles/5/graze/
    url(r'^(?P<profile_id>\d+)/graze/$',
        views.grazeProfile, name='grazeProfile'),
    #/profiles/5/post/5/graze/
    url(r'^(?P<profile_id>\d+)/post/(?P<post_id>\d+)/graze/$',
        views.grazePost, name='grazePost'),
    #/profiles/createprofile/2/
    url(r'^createprofile/(?P<species_id>\d+)/$',
        views.createProfile, name='createProfile'),
)

openspace/apps/tags/urls.py
from django.conf.urls import patterns, url
from apps.tags import views

urlpatterns = patterns('',
    #/tags/
    url(r'^$', views.tags, name='tags'),
    #/tags/2/
    url(r'^(?P<tag_id>\d+)/$',
        views.tag, name='tag'),
    #/tags/2/selecttrail
    url(r'^(?P<tag_id>\d+)/selecttrail/$',
        views.selectTrail, name='selectTrail'),
)

openspace/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.cache import cache_page
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from django.contrib import admin
from apps.profiles.models import Profile
from openspace import views
from sitemap import *

admin.autodiscover()

handler404 = 'views.openspace404'
handler500 = 'views.openspace500'

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^data/$', views.dataPage, name='dataPage'),
    url(r'^help/$', views.helpPage, name='helpPage'),
    url(r'^credits/$', views.creditsPage, name='creditsPage'),
    url(r'^profiles/', include('apps.profiles.urls', namespace='profiles')),
    url(r'^tags/', include('apps.tags.urls', namespace='tags')),
    url(r'^search/$', views.parkSearch, name='parkSearch'),
    url(r'^topprofiles/$', views.topProfiles, name='topProfiles'),
    url(r'^topposts/$', views.topPosts, name='topPosts'),
    url(r'^changebg/$', views.changeBg, name='changeBg'),
    url(r'^humanentry/(?P<human_key>\d+)$', views.humanEntry, name='humanEntry'),
    url(r'^resetsession/$', views.resetSession, name='resetSession'),
    url(r'^nonewsession/', views.noNewSession, name='noNewSession')
)


# here be monsters ... and sitemap garbage
info_dict = {
    'queryset': Profile.objects.all(),
    'date_field': 'date_published'
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'profiles': GenericSitemap(info_dict, priority=0.6),
}

urlpatterns += patterns('',
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

openspace/apps/profiles/models.py
from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from apps.tags.models import Tag
from libs.siteEnums import Gender, Species, System
from libs.auxHelpers import returnCount
from random import randint
import os, fnmatch
from os.path import join
from settings.common import STATIC_URL


class Profile(models.Model):
    """Profile objects are the primary object employed in the openspace wilderness.
    
    Profiles may have a profile image, an icon, and related data
    + may have sets of friends containing Profile objects
    + may have sets of tags containing Tag objects
    + have a one-to-one relationship with Post objects
    
    Required assignments:
    fname, lname, age
    
    Optional assignments:
    location, blog_url, blog_id, last_login, friends, tags
    
    Default assignments:
    gender = female(0)
    interest = 0
    energy = 1
    meals = 0
    visible = True
    species = abandoned(0)
    """
    
    position = models.PositiveIntegerField(max_length=9, default=1)
    fname = models.CharField('First Name', max_length=35)
    lname = models.CharField('Last Name', max_length=35)
    gender = models.PositiveIntegerField(max_length=2, default=Gender.female)
    age = models.CharField(max_length=5)
    location = models.CharField(max_length=75, blank=True)
    blog_url = models.URLField(blank=True)
    blog_id = models.CharField(max_length=5, blank=True)
    last_login = models.DateField('last login', blank=True, null=True)
    friends = models.ManyToManyField('self', blank=True)
    img_number = models.PositiveIntegerField(max_length=4, default=1)
    tags = models.ManyToManyField(Tag, blank=True)
    interest = models.PositiveIntegerField(max_length=5, default=0)
    energy = models.PositiveIntegerField(max_length=4, default=1)
    meals = models.PositiveIntegerField(max_length=3, default=0)
    visible = models.BooleanField(default=True)
    species = models.PositiveIntegerField(max_length=1, default=Species.abandoned)
    
    @cached_property
    def fullName(self):
        return self.fname + ' ' + self.lname
    
    @cached_property
    def sex(self):
        if self.gender == Gender.female:
            return 'female'
        else:
            return 'male'
    
    @property
    def imageString(self):
        return str(self.img_number)
    
    @property
    def interestString(self):
        return str(self.interest)
    
    @property
    def energyString(self):
        return str(self.energy)
            
    @property
    def speciesReadable(self):
        if self.species == Species.abandoned:
            return 'abandoned'
        elif self.species == Species.system:
            return 'system'
        elif self.species == Species.visitor:
            return 'visitor'
        elif self.species == Species.predator:
            return 'predator'
        elif self.species == Species.forager:
            return 'forager'
        elif self.species == Species.dead:
            return 'dead'
        else:
            return 'unknown'
        
    @property
    def isActive(self):
        if self.species == Species.predator or self.species == Species.forager:
            return True
    
    @property
    def isPredator(self):
        if self.species == Species.predator:
            return True
    
    @property
    def isForager(self):
        if self.species == Species.forager:
            return True
    
    @property
    def isFull(self):
        if self.energy >= System.full:
            return True
    
    @property
    def isDead(self):
        if self.species == Species.dead:
            return True
    
    @cached_property
    def fitUrl(self):
        if len(self.blog_url) > System.fitUrl:
            return self.blog_url[7:]
        return self.blog_url
    
    @property
    def prettyPic(self):
        return 'media/' + self.speciesReadable + '/profilepic-' + self.imageString + '.jpg'
    
    @property
    def prettyIcon(self):
        return 'media/' + self.speciesReadable + '/icon-' + self.imageString + '.jpg'
    
    @property
    def decentFriends(self):
        return self.friends.filter(visible=True).order_by('lname')
    
    @property
    def bestFriends(self):
        return self.decentFriends[:System.bestFriends]
    
    @property
    def topTags(self):
        return self.tags.all().order_by('-interest')[:8]
    
    @property
    def recentActivity(self):
        return self.post_set.all().order_by('-date_published')[:3]
    
    def __unicode__(self):
        return self.fullName
        
    def drain(self):
        self.energy -= 1
        if self.energy <= 0:
            self.die()
        self.save()
    
    def die(self):
        self.species = Species.dead
        self.energy = 0
        self.visible = True
        self.last_login = timezone.now() 
        self.img_number = randint(1, returnCount('dead')/2)
        self.save()


class Post(models.Model):
    """Post objects contain content from recovered blogger blogs
    or activity from the active Profile types
    
    Required assignments:
    post_profile = Profile object, post_content
    
    Optional assignments:
    tags
    
    Default assignments:
    date_published = timezone.now(), interest = 0, just_posted = False
    """

    post_profile = models.ForeignKey(Profile)
    date_published = models.DateTimeField('date published',
        default=timezone.now())
    post_content = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True)
    interest = models.PositiveIntegerField(max_length=5, default=0)
    just_posted = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date_published']
    
    @cached_property
    def postProfileName(self):
        return self.post_profile.fullName
    
    @cached_property
    def fitContent(self):
        return self.post_content[:300]
    
    @property
    def interestString(self):
        return str(self.interest)
    
    @property
    def justPosted(self):
        if self.just_posted:
            self.just_posted = False
            self.save()
            return True
    
    def __unicode__(self):
        return str(self.post_profile) + ' / ' + self.post_content[:11]


class Comment(models.Model):
    """Comments are short content that can be created by a Profile and attached to a Post
    
    Required assignments:
    comment_profile = Profile object, comment_post = Post object, comment_content
    
    Default assignments:
    date_published = timezone.now()
    """

    comment_profile = models.ForeignKey(Profile)
    comment_post = models.ForeignKey(Post)
    date_published = models.DateTimeField('date published',
        default=timezone.now())
    comment_content = models.TextField()
    
    class Meta:
        ordering = ['-date_published']
    
    @cached_property
    def commentProfileId(self):
        return self.comment_profile_id
    
    @cached_property
    def commentPostId(self):
        return self.comment_post_id
    
    @cached_property
    def commentPostProfileId(self):
        return Post.objects.get(id=self.comment_post_id).post_profile_id
    
    def __unicode__(self):
        return str(self.comment_profile) + ' / ' + self.comment_content[:11]

openspace/apps/tags/models.py
from django.db import models

# TAG MODEL
class Tag(models.Model):
    """Tag model can be applied to Profiles and Posts.
    
    Tags consist of a Tag name and an interest value based on how many times a Tag
    had been applied. 
    Trails of similarly tagged Profiles are automatically created for navigation
    """
    
    name = models.CharField(max_length=15)
    interest = models.PositiveIntegerField(max_length=6, default=0)
    
    @property
    def interestString(self):
        return str(self.interest)
    
    def __unicode__(self):
        return self.name

openspace/apps/profiles/forms.py
from django import forms
from apps.profiles.models import Comment
from apps.tags.models import Tag

class CommentForm(forms.ModelForm):
    
    class Meta:
        auto_id = False
        model = Comment
        fields = ('comment_content',)
        widgets = {
            'comment_content': forms.Textarea(
                attrs = {'cols': 68, 'rows': 7, 'class': 'allRound'}),
        }
        
class PostTagForm(forms.Form):
    post_new_tags = forms.CharField(label='',
        widget = forms.TextInput(attrs={'size':'93', 'class': 'formP'}))

class ProfileTagForm(forms.Form):
    pro_new_tags = forms.CharField(label='', widget = forms.TextInput(attrs={'size': '54'}))

openspace/apps/tags/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from apps.profiles.models import Profile
from apps.tags.models import Tag
from libs import profileHelpers, siteHelpers
from libs.siteEnums import Tags

#/tags/
def tags(request):
    context = {'tags': Tag.objects.exclude(interest=0).filter(id__gt=7).order_by('name')}
    return render(request, 'tags/trails.html', context)

#/tags/<tag_id>/
def tag(request, tag_id):
    """Display paginate Profiles assigned to current Tag."""
    tag = get_object_or_404(Tag.objects.prefetch_related('profile_set'), pk=tag_id)
    unpagedProfiles = Profile.objects.filter(tags=tag).order_by('-interest')
    pagedResults = siteHelpers.paginatorMaker(unpagedProfiles, request.GET.get('page'), 25)
    context = {
        'special': True,
        'tag': tag,
        'count': unpagedProfiles.count(),
        'paged_results': pagedResults
    }
    return render(request, 'profile-results.html', context)
    
#/tags/<tag_id>/selecttrail/
def selectTrail(request, tag_id):
    """Assigns a Tag to user's session navigation."""
    tag = get_object_or_404(Tag, pk=tag_id)
    if tag.interest > 0:
        if request.session['selected_trail'] == tag.name:
            request.session['selected_trail'] = 'no'
            request.session['notification'] = 'trail'
        else:
            request.session['selected_trail'] = tag.name
            request.session['notification'] = 'trail'
    else:
        request.session['notification'] = 'nope'
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

openspace/apps/profiles/templates/profiles/empty-set.html
<div class="box bigBox allround">
    <div class="vCenter">
        <h4>nothing here, move along please</h4>
    </div>
</div>

openspace/apps/profiles/templates/profiles/friends.html
{% extends 'profiles/profile-base.html' %}
{% block pagetitle %}{{ profile.fullName }}'s  [ friends ]{% endblock %}
{% block profile_meat %}
<div id="allFriends" class="box">
    <div class="heading">
        <h3>{{ profile.fullName }}'s friends [ {{ profile.decentFriends.count }} ]</h3>
    </div>
    
    <div class="content">
        {% if profile.decentFriends %}{% for friend in profile.decentFriends %}<div class="innerListing">
            <a href="{% url 'profiles:single' friend.id %}"><img class="jsFade icon allRound" src="{{ STATIC_URL }}{{ friend.prettyIcon }}" alt="friend icon" /></a>
            <h5><a href="{% url 'profiles:single' friend.id %}">{{ friend.fullName }}</a></h5>
            <h5><span class="light"><em>{{ friend.last_login }}</em></span></h5>
            <div class="clear"></div>
        </div>{% endfor %}
        <div class="clear"></div>
        {% else %}<p class="vCenter">[ {{ profile.fullName }} ] has no friends</p>{% endif %}
    </div>
</div>
<div class="box gray">
    <div class="content vCenter">
        <h4 class="strong"><a href="{% url 'profiles:single' profile.id %}">view all posts</a> [ {{ profile.post_set.count }} ]</h4>
    </div>
</div>
{% endblock %}

openspace/apps/profiles/templates/profiles/post-comment.html
<div class="hiddenToggle box gray" id="leave-comment{{ post.id }}">
    <div class="heading">
        <h3>[ + ] {{ post.date_published }}</h3>
    </div>
        
    <div class="content">
        <form id="{{post.id}}" class="formal" method="Post" action="{%url 'profiles:addComment' profile.id post.id %}">
            {% csrf_token %}{% for field in comment_form %}<div id="{{ post.id }}_comment">{{ field }}</div>{% endfor %}
            <input type="submit" class="button" value="add comment" />
        </form>
    </div>
</div>

openspace/apps/profiles/templates/profiles/post-display.html
<div class="post allRound"> <!-- POST -->
    <div class="auxAct mono small">
        <a data-mark="add-tags{{ post.id }}" class="toggle">[tag]</a><a href="{% url 'profiles:postInterest' post.id %}">[+]</a>
    </div>
    
    <div class="content">
        <a href="{% url 'profiles:single' profile.id %}"><img class="jsFade icon allRound" src="{{ STATIC_URL }}{{ profile.prettyIcon }}" alt="profile icon" /></a>
        <div class="name">
            <h4><a href="{% url 'profiles:single' profile.id %}">{{ profile.fullName }}</a></h4>
            <h5 class="strong"><a href="{% url 'profiles:singlePost' profile.id post.id %}">{{ post.date_published|date:"F j, Y - fA" }}</a></h5>
        </div>
        <div class="clear"></div>
        <p class="topLine">{{ post.post_content|safe }}</p>
        <h5>interest [ {{ post.interest }} ]</h5> 
        <p>{% for tag in post.tags.all %}<a href="{% url 'tags:tag' tag.id %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    </div>
      
    <div class="comments"> <!-- COMMENTS -->
        <div class="content">
            <p>{{ post.comment_set.count }} comment{% if post.comment_set.count != 1 %}s{% endif %} <span class="mono"><a data-mark="leave-comment{{ post.id }}" class="toggle">[comment]</a></span></p>
        </div>
        {% if post.comment_set.count > 0 %}{% for com in post.comment_set.all %}<div class="comment">
            <h5><a href="{% url 'profiles:single' com.comment_profile.id %}">{{ com.comment_profile }}</a> - <em>{{ com.date_published|date:"F j, Y - fA" }}</em></h5>
            <p>{{ com.comment_content }}</p>
        </div>{% endfor %}
        <div class="clear butt"></div>{% endif %}    
    </div> <!-- END comments --> 
</div> <!-- END post -->
{% include 'profiles/post-comment.html' %}
{% include 'profiles/post-tags.html' %}

openspace/apps/profiles/templates/profiles/post-tags.html
<div class="hiddenToggle box gray" id="add-tags{{ post.id }}">
    <div class="heading">
        <h3>[ + ] tags</h3>
    </div>
        
    <div class="content">
        <form class="formal" id="{{ post.id }}_post_tag_form" method="Post" action="{% url 'profiles:addPostTags' profile.id post.id %}">
            {% csrf_token %}{% for field in post_tag_form %}<div id="{{ post.id }}_post_new_tags">{{ field }}</div>{% endfor %}
            <input type="submit" class="button" value="add tags" />
        </form>
        <div class="clear"></div>
        <p class="small justify mono">{% for tag in auto_tags %}<a data-flag="{{post.id}}" data-tag="{{ tag.name|lower }}" class="postTag">{{ tag.name|lower }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    </div>
</div>

openspace/apps/profiles/templates/profiles/profile-base.html
{% extends 'base.html' %}
{% block pagetitle %}{{ profile.fullName }}{% endblock %}
{% block body %}<div id="leftCol" class="col">
    <div id="profile" class="box">
        <div class="heading">
            <a href="{% url 'profiles:single' profile.id %}"><h3>{{ profile.fullName }}</h3></a>
            <div class="auxAct mono small">{% if not is_friend %}<a href="{% url 'profiles:makeFriend' profile.id %}">[f]</a>{% endif %}<a data-mark="profile-tags{{ profile.id }}" class="toggle">[tag]</a><a href="{% url 'profiles:profileInterest' profile.id %}">[+]</a></div>
        </div>
        <div class="content">
            <div id="picWrapper">
                <div id="profilePic">
                    <a href="{% url 'profiles:single' profile.id %}"><img class="jsFade round" src="{{ STATIC_URL }}{{ profile.prettyPic }}" alt="profile picture" /></a>
                </div>
            </div>
            <div id="profileData">
                <h4>{{ profile.age }} years old</h4>
                <h4><em>{{ profile.sex }}</em></h4>
                <h4>{{ profile.location }}</h4>
                <p class="small space"></p>
                <h4 class="small topLine">interest [ {{ profile.interest }} ]</h4>
                <p class="topTags small">{% for tag in profile.topTags %}<a href="{% url 'tags:tag' tag.id %}">{{ tag.name|lower }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            </div>
            <div class="clear"></div>
        </div>
    </div> <!-- END profile box -->
    {% include 'profiles/profile-tags.html' %}
    {% if profile.blog_url %}<div id="url" class="box gray">
        <div class="content vCenter">
            <h4 class="strong"><a href="{{ profile.blog_url }}" target="_blank">{{ profile.fitUrl }}</a></h4>
        </div>
    </div> <!-- END url box -->{% endif %}
    <div id="friends" class="box">
        <div class="heading">
            <h3>friends</h3>
        </div>
        <div class="content">
            <h4><a href="{% url 'profiles:friends' profile.id %}">view all friends</a> [ {{ profile.decentFriends.count }} ]</h4>
            {% if profile.decentFriends %}<ul class="friends">
            {% for friend in profile.bestFriends %}<li><a href="{% url 'profiles:single' friend.id %}"><img class="jsFade icon" src="{{ STATIC_URL }}{{ friend.prettyIcon }}" alt="friend icon" /></a></li>{% endfor %}
            </ul>
            {% else %}<br/><p>{{ profile.fullName }} has no friends</p>{% endif %}
            <div class="clear"></div>
        </div>
    </div> <!-- END friends box -->
    <div id="posts" class="box">
        <div class="heading">
            <h3>views</h3>
        </div>
        <div class="content">
            <h4><a href="{% url 'profiles:single' profile.id %}">view all posts</a> [ {{ profile.post_set.count }} ]</h4>
            <h4><a href="{% url 'profiles:profileTags' profile.id %}">view all tags</a> [ {{ profile.tags.count }} ]</h4>
        </div>
    </div> <!-- END posts box --> 
</div> <!-- END lColWrap -->
<div id="rightCol" class="col"> <!-- rColWrap -->
    <div id="lastLogin" class="box gray">
        <div class="content vCenter">
            <h4 class="strong"><span class="light">last login</span> [ {{ profile.last_login|date:"F d, Y"}} ]</h4>
        </div>
    </div> <!-- END lastLogin box -->
    {% block profile_meat %}{% endblock %} <!-- all posts -->
</div> <!-- END rColWrap -->{% endblock %}

openspace/apps/profiles/templates/profiles/profile-tags.html
<div class="hiddenToggle box gray" id="profile-tags{{ profile.id }}">
    <div class="heading">
        <h3>[ + ] tags</h3>
    </div>
        
    <div class="content">
        <form class="formal" id="{{ profile.id }}_profile_tag_form" method="Post" action="{% url 'profiles:addProfileTags' profile.id %}">
            {% csrf_token %}{% for field in profile_tag_form %}<div id="{{ profile.id }}_profile_new_tags">{{ field }}</div>{% endfor %}
            <input type="submit" class="button" value="add tags" />
        </form>
        <div class="clear"></div>
        <p class="small justify mono">{% for tag in auto_tags %}<a data-id="{{ profile.id }}" data-tag="{{ tag.name|lower }}" class="profileTag">{{ tag.name|lower }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    </div>
</div>

openspace/apps/profiles/templates/profiles/single-post.html
{% extends 'profiles/profile-base.html' %}
{% block pagetitle %} {{ post.date_published }}{% endblock %}
{% block profile_meat %}
{% include 'profiles/post-display.html' %}
<div class="box gray">
    <div class="content vCenter">
        <h4 class="strong"><a href="{% url 'profiles:single' profile.id %}">view all posts</a> [ {{ profile.post_set.count }} ]</h4>
    </div>
</div>
{% endblock %}

openspace/apps/profiles/templates/profiles/single-profile.html
{% extends 'profiles/profile-base.html' %}
{% block profile_meat %}
{% if posts.has_next or posts.has_previous %}<div id="pagination" class="box mono vCenter small">
{% if posts.has_previous %}<a href="?page={{ posts.previous_page_number }}"><<</a>{% endif %}
post page [{{ posts.number }} of {{ posts.paginator.num_pages }}]
{% if posts.has_next %}<a href="?page={{ posts.next_page_number }}">>></a>{% endif %}</div>{% endif %}
{% for post in posts %}{% include 'profiles/post-display.html' %}{% endfor %}
{% if posts.has_next or posts.has_previous %}<div id="pagination" class="box mono vCenter small">
{% if posts.has_previous %}<a href="?page={{ posts.previous_page_number }}"><<</a>{% endif %}
post page {{ posts.number }} of {{ posts.paginator.num_pages }}
{% if posts.has_next %}<a href="?page={{ posts.next_page_number }}">>></a>{% endif %}</div>{% endif %}
{% endblock %}

openspace/apps/profiles/templates/profiles/tags.html
{% extends 'profiles/profile-base.html' %}
{% block pagetitle %}{{ profile.fullName }}'s  [ tags ]{% endblock %}
{% block profile_meat %}
<div id="friends" class="box">
    <div class="heading">
        <h3>{{ profile.fullName }}'s tags [ {{ profile.tags.count }} ]</h3>
    </div>
    <div class="content">
        {% if profile.tags.all.count > 0 %}{% for tag in profile.tags.all %}<div class="innerListing">
            <a href="{% url 'tags:selectTrail' tag.id %}">[ {% if selected_trail == tag.name %}&ndash;{% else %}@{% endif %} ]</a> <a href="{% url 'tags:tag' tag.id %}">{{ tag.name }}</a> [ {{ tag.interest }} ]
        </div>{% endfor %}
        {% else %}<p class="vCenter">[ {{ profile.fullName }} ] has no tags yet</p>{% endif %}
        <div class="clear"></div>
    </div>
</div>
<div class="box gray">
    <div class="content vCenter">
        <h4 class="strong"><a href="{% url 'profiles:single' profile.id %}">view all posts</a> [ {{ profile.post_set.count }} ]</h4>
    </div>
</div>
{% endblock %}